### PR TITLE
Log the modified extension settings as part of Log Diagnostics

### LINKED ISSUE #11700: Add setting values to Log Diagnostics output
Opening this issue to track adding all relevant effective settings values, to the output of the Log Diagnostics command.  That way, we wouldn't need to rely on users to provide this information separately and figure out the various settings location.

### PR DESCRIPTION
**Pull request by bobbrow**
Fixes: #11700

ex:
```
Modified Settings:
{
    "C_Cpp.default.compilerPath": "C:\\Program Files\\Microsoft Visual Studio\\2022\\Preview\\VC\\Tools\\Llvm\\x64\\bin\\clang++.exe",
    "C_Cpp.loggingLevel": "Debug"
}
```

### CODE REVIEW

**Comment by sean-mcmanus** [comment]
I don't see files.associations logged -- is that intentional? I'm guessing it is.

**Comment by sean-mcmanus** [comment]
Also, I don't see `"C_Cpp.files.exclude"` logged -- that seems unintentional?

**Comment by bobbrow** [comment]
I'll take a look at the complex types @sean-mcmanus. I pushed this without testing all of the different types and encountered a bug in the settings tracker around integer vs. number too.  Moving this PR to draft for now...

**Comment by sean-mcmanus** [comment]
@bobbrow Yeah, for example
image

**Comment by bobbrow** [comment]
@sean-mcmanus this should address your previous comments now.  I did not log editor settings, only those in the `C_Cpp` block.  If I get time later this week I might add a few of the other settings that our extension tracks.

**Review by sean-mcmanus — APPROVED** [review]

**Pull request merged**
