### PR TITLE
Update FAQs.md

### PR DESCRIPTION
**Pull request by jogo-**
Missing whitespace

### CODE REVIEW

**Review by YassinMahmoudEl-Zouhery — COMMENTED** [review]
I think it's not working

**Review by bobbrow — APPROVED** [review]

**Comment by YassinMahmoudEl-Zouhery** [comment]
Ok great

**Comment by YassinMahmoudEl-Zouhery** [comment]
@jogo- @bobbrow 
screenshot from 2019-01-20 00-45-11

**Comment by YassinMahmoudEl-Zouhery** [comment]
how about that

**Comment by YassinMahmoudEl-Zouhery** [comment]
Can i now so i can do the other one

**Comment by YassinMahmoudEl-Zouhery** [comment]
bobbrow

**Comment by sean-mcmanus** [comment]
@MickeyElZouhery What's the issue? I don't understand.

**Comment by YassinMahmoudEl-Zouhery** [comment]
@sean-mcmanus look ask @jogo- or @bobbrow  because  i don't think i will tell you the right issue

**Comment by bobbrow** [comment]
This PR was already merged.  There is no remaining issue here.

**Comment by YassinMahmoudEl-Zouhery** [comment]
ok

**Comment by YassinMahmoudEl-Zouhery** [comment]
if there is any issue just tell me

**Pull request merged**
