### PR TITLE
Change C/C++ taskSourceStr to shell.

### LINKED ISSUE #5388: The task provider for "C/C++" tasks unexpectedly provided a task of type "shell".
VSCode version:
```
1.45.0-insider
a0fe37870c42e0704a492cdc6b8550b4cf23f63c
x64
```
vscode-cpptools version: `0.28.0-insiders`

Here is my `tasks.json`.
```json
{
	"version": "2.0.0",
	"tasks": [
		{
			"label": "gen",
			"type": "shell",
			"command": "cmake",
			"args": [
				"-DCMAKE_BUILD_TYPE=DEBUG",
				".."
			],
			"options": {
				"cwd": "build"
			}
		},
		{
			"label": "make",
			"type": "shell",
			"command": "make",
			"args": [
				
			],
			"group": {
				"kind": "test",
				"isDefault": true
			},
			"dependsOn": "gen",
			"options": {
				"cwd": "build"
			}
		},
		{
			"label": "run",
			"type": "shell",
			"command": "./build/infidungeon",
			"args": [
				
			],
			"group": {
				"kind": "build",
				"isDefault": true
			},
			"dependsOn": "make"
		}
	]
}
``` 

If I change my code, or otherwise sometimes completely randomly, when I run task `run`, I get this message:
image
And when I hit, "Show output" I see:
```
The task provider for "C/C++" tasks unexpectedly provided a task of type "shell".
The task provider for "C/C++" tasks unexpectedly provided a task of type "shell".
```

Is something wrong with my `tasks.json`? I can't replicate this consistently? This does not happen when all extensions are disabled.

### PR DESCRIPTION
**Pull request by sean-mcmanus**
Fixes https://github.com/microsoft/vscode-cpptools/issues/5388

### CODE REVIEW

**Review by Colengms — APPROVED** [review]

**Comment by sean-mcmanus** [comment]
The build task runs fine, but there's some breakage in the debugging part, that causes the debugger to not launch -- I haven't figured out why yet (everything seems okay when debugging it).

**Comment by sean-mcmanus** [comment]
> The build task runs fine, but there's some breakage in the debugging part, that causes the debugger to not launch -- I haven't figured out why yet (everything seems okay when debugging it).

I'm getting Error: Configuration 'g++.exe - Build and debug active file' is missing in 'launch.json'.

**Comment by sean-mcmanus** [comment]
> > The build task runs fine, but there's some breakage in the debugging part, that causes the debugger to not launch -- I haven't figured out why yet (everything seems okay when debugging it).
> 
> I'm getting Error: Configuration 'g++.exe - Build and debug active file' is missing in 'launch.json'.

Oh...that appears to be normal...it catches the failure and then runs startDebugging without an exception.

**Comment by sean-mcmanus** [comment]
Oh -- this works -- I just didn't have some OpenDebugAD7 files installed.

**Review by bobbrow — APPROVED** [review]

**Pull request merged**
