### PR TITLE
Retry more.

### PR DESCRIPTION
**Pull request by sean-mcmanus**
Add more retries. The failure issue today would fix itself if it retried more, but I'm not sure what the ideal retry amount is because the issue stopped reproing. Maybe we could check telemetry afterwards to see if the number of failures decreased.

### CODE REVIEW

**Comment by Colengms** [comment]
Depending on what caused the error, retries might not help.  The outage seemed to repro consistently for certain systems, and for quite a while (an hour?).  If a DNS issue, a client machine might keep retrying with the cached IP it got from an earlier DNS request.

**Review by Colengms — APPROVED** [review]

**Comment by sean-mcmanus** [comment]
> Depending on what caused the error, retries might not help. The outage seemed to repro consistently for certain systems, and for quite a while (an hour?). If a DNS issue, a client machine might keep retrying with the cached IP it got from an earlier DNS request.

Yeah, but in this particular incident, I was seeing the failures be random, so retrying fixed it if enough retries were done.

**Comment by bobbrow** [comment]
I think it's too many retries.  This is supposed to be about the developer's connection being bad, not about potential CDN incidents.

**Comment by sean-mcmanus** [comment]
@bobbrow I reduced the max delay between retries to 15 seconds: https://github.com/microsoft/vscode-cpptools/pull/7883 .

**Pull request merged**
