### PR TITLE
Update c_cpp_properties.json.md

### PR DESCRIPTION
**Pull request by sean-mcmanus**
Change "$[" to "${" and workspaceRoot to workspaceFolder.

### CODE REVIEW

**Comment by bobbrow** [comment]
oops.  I didn't see this and I already fixed it.

**Comment by bobbrow** [comment]
oh, but you changed workspaceRoot too.  Merged with my other change.

**Review by bobbrow — APPROVED** [review]

**Comment by sean-mcmanus** [comment]
What's up with this? Are you going to merge it?

**Comment by bobbrow** [comment]
It was your change, so I thought I would let you merge it.  Either way...  I clicked the button just now.

**Pull request merged**
