### PR TITLE
Reprompt on c_cpp_properties.json deletion.

### PR DESCRIPTION
**Pull request by sean-mcmanus**
Fix for #3088.

### CODE REVIEW

**Comment by sean-mcmanus** [comment]
I'm not done testing this -- there may be some bugs, but now I'm not sure how I reproed them yet.

**Comment by sean-mcmanus** [comment]
c_cpp_properties.json gets created from the prompt if it doesn't exist, but for the configurationProvider prompt it adds it to the default.configurationProvider -- is that intentional? The difference in behavior confused me.

**Comment by sean-mcmanus** [comment]
I can't full test this until the bug with c_cpp_properties.json deletion causing creation to fail is fixed.

**Comment by sean-mcmanus** [comment]
This pull request is just needs further testing -- the last time I tried to test it, another bug was interfering with my testing, but that got fixed and I never got around to re-test.

**Comment by ThadHouse** [comment]
This won't pop up if settings.json is used to set defaults, right? We use the provider API and have noticed random bugs that happen when the API is used and a user accidentally adds c_cpp_properties.json without understanding. We always recommend our users delete that file if they see it, and I don't want this to be come a feedback loop.

**Comment by sean-mcmanus** [comment]
> This won't pop up if settings.json is used to set defaults, right? We use the provider API and have noticed random bugs that happen when the API is used and a user accidentally adds c_cpp_properties.json without understanding. We always recommend our users delete that file if they see it, and I don't want this to be come a feedback loop.

I'm not sure, but when I have time to revisit this, I'll double check that the config prompts don't appear if the configuration provider (or compileCommands) is already set via the settings.json.

**Comment by bobbrow** [comment]
This was addressed with PR #4987.

**Pull request closed without merging**
