### PR TITLE
Seanmcm/0 16 0 release2

### PR DESCRIPTION
**Pull request by sean-mcmanus**

### CODE REVIEW

**Review by bobbrow — CHANGES_REQUESTED** [review]
why isn't this a merge from master?

**Comment by sean-mcmanus** [comment]
I modified the date in the changelog.md. Otherwise, it's a merge from master, right? Oh, maybe I should put the changelog.md change into master before merging to release?

**Comment by bobbrow** [comment]
yes, please go to master first

**Comment by bobbrow** [comment]
do you have admin merge rights?  You can skip the Travis build for this since it's just a txt file update

**Comment by sean-mcmanus** [comment]
Not sure if I have merge rights.

**Comment by bobbrow** [comment]
Then i can do it if you submit the changes in the next few minutes (or I can start a branch if you want)

**Pull request closed without merging**
