### PR TITLE
default to c++14 on mac for build and run active file

### PR DESCRIPTION
**Pull request by bobbrow**
This is a temporary workaround to enable users to compile the code in the getting started guide/walkthrough without having to create and edit tasks.json.

### CODE REVIEW

**Review by Colengms — DISMISSED** [review]

**Review by sean-mcmanus — APPROVED** [review]
Is c++14 sufficient or was it c++17?

**Review by sean-mcmanus — CHANGES_REQUESTED** [review]
Wait a sec -- won't this break C users, i.e. when F5 is done with a .c file?

error: invalid argument '-std=c++14' not allowed with 'C'

i.e. can you add a check for the file extension before adding that -std flag?

**Comment by sean-mcmanus** [comment]
Also, I believe the default would be a GNU version like "gnu14++" instead of "c++14".

**Comment by bobbrow** [comment]
> Is c++14 sufficient or was it c++17?

c++14 was sufficient in my tests.  I was thinking c+11 was also sufficient, I'd need to check again...

> Wait a sec -- won't this break C users, i.e. when F5 is done with a .c file?

Good catch.

> Also, I believe the default would be a GNU version like "gnu++14" instead of "c++14".

I thought that was primarily for g++, not clang.  Is it?

**Comment by sean-mcmanus** [comment]
The default for apple clang is currently gnu++99 according to the docs at https://opensource.apple.com/source/clang/clang-137/src/tools/clang/docs/UsersManual.html .

**Comment by bobbrow** [comment]
Latest change is not tested yet.  Don't check in yet.  I'll validate this tomorrow.

**Comment by bobbrow** [comment]
Tested on mac. This is ready for review.

**Review by sean-mcmanus — APPROVED** [review]

**Review by Colengms — APPROVED** [review]

**Pull request merged**
