### PR TITLE
Update description for references.maxCachedProcesses

### PR DESCRIPTION
**Pull request by bobbrow**
Addresses insiders feedback in #4036

### CODE REVIEW

**Comment by sean-mcmanus** [comment]
No, the 0 default is "by design". I believe it should be opt-in and not to use the null default.

**Review by sean-mcmanus — CHANGES_REQUESTED** [review]
...see my comment.

**Comment by bobbrow** [comment]
Hmm... We need to update the description then.

**Comment by sean-mcmanus** [comment]
Sure, I'm okay with the updated description -- but the default value was intentionally left out because it's not really necessary to describe the default since it shows in the UI...but we do for some settings, so I'm not sure what the best practice is in regards to that.

**Review by sean-mcmanus — APPROVED** [review]

**Comment by bobbrow** [comment]
I think one of the problems here is that the other maxCachedProcesses settings do not disable the feature when you set it to 0.  They have a min value of 2 internally, but this one does not.  Setting it to 0 here turns it off.

**Comment by sean-mcmanus** [comment]
> I think one of the problems here is that the other maxCachedProcesses settings do not disable the feature when you set it to 0. They have a min value of 2 internally, but this one does not. Setting it to 0 here turns it off.

What's the problem? Yeah, I wasn't sure about whether the internal min value of 2 should be propogated to the TypeScript's min value or not.

**Review by michelleangela — APPROVED** [review]

**Comment by bobbrow** [comment]
The problem is that the settings all have the same name, but not the same defaults, so I wanted to document it better.

**Pull request merged**
