### PR TITLE
Support Debug Welcome Panel

### PR DESCRIPTION
**Pull request by WardenGnaw**
This PR enables the Debug Welcome Panel for c/cpp languages.

This allows us to add content to the Debug Welcome Screen (no .vscode tasks or launch). at the moment I am just adding the C/C++ documentation. 
 
image

Clicking on “Run and Debug” gives the “Run and Debug Active File” experience.
 
image
image

Linked Issue: https://github.com/microsoft/vscode-cpptools/issues/4837

### CODE REVIEW

**Review by pieandcakes — APPROVED** [review]

**Comment by WardenGnaw** [comment]
@jureid

**Comment by jureid** [comment]
@WardenGnaw which document does this link to?

**Comment by WardenGnaw** [comment]
@jureid https://code.visualstudio.com/docs/languages/cpp

**Comment by jureid** [comment]
Got it. I think it might be more helpful to link to this [debug config doc](https://code.visualstudio.com/docs/cpp/launch-json-reference), since at this point the customer is probably trying to learn about launch.json as they need to create one.
 
Then we can change the button text to "Learn more about launch.json" or "Learn more about configuring C/C++ debugging".

Also, is the primary action we want customers to take to click on "Run and debug"? If so, maybe the link to documentation should just be a string with a hyperlink rather than a button:

"To learn more about launch.json, see [Configuring C/C++ debugging](https://code.visualstudio.com/docs/cpp/launch-json-reference)." 

Let me know what you think.

**Review by sean-mcmanus — APPROVED** [review]

**Pull request merged**
