### PR TITLE
Allow extension's x64 binaries to run on Apple Silicon x64 emulator

### PR DESCRIPTION
**Pull request by xymeng16**
Since arm64 and x86 macOS should have identical C++ support and features, I simply modified the if-condition in the activation() function at main.ts to allow the extension to work on my M1-chip Macbook. Now it has worked for 1 week with no error.

### CODE REVIEW

**Review by sean-mcmanus — APPROVED** [review]

**Comment by sean-mcmanus** [comment]
FYI, the cpptools and cpptools-srv binaries are built for x64, so they may run slower and/or use more battery via running in an emulated mode compared to native arm64 binaries would.

**Comment by WardenGnaw** [comment]
Same with the debugger binaries.

The mono runtime shipped is built for macOS x64 and same with the lldb-mi that is built.

**Comment by michelleangela** [comment]
Also note that some default IntelliSense configuration may need to be modified, as these settings are based on the host architecture, platform, and available compiler.

**Comment by xymeng16** [comment]
It seems that cpptools and cpptools-srv are close-sourced (or I don't know where to fetch their code). Hope that native arm64 version binaries will be online soon. Thanks for all of your work!

**Comment by sean-mcmanus** [comment]
@xymeng16 We're tracking that with https://github.com/microsoft/vscode-cpptools/issues/6595 .

**Pull request merged**
