### PR TITLE
Don't send file change notifications for excluded files

### PR DESCRIPTION
**Pull request by bobbrow**
I recently noticed a lot of `cpptools/fileChanged` notifications for files in the `.git` folder.  To reduce the noise, I'm filtering out those files that we're treating as excluded.

### CODE REVIEW

**Comment by sean-mcmanus** [comment]
The processing is already excluded in cpptools -- it's just logging you're seeing. Are you sure you want this change?

**Comment by sean-mcmanus** [comment]
The pattern matching code on the cpptools side doesn't exactly match the one you're using here.

**Comment by sean-mcmanus** [comment]
I think the LSP handler in cpptools could be changed to not log for those messges and logging could be added when the file isn't excluded. That seems like a better fix to me.

**Comment by bobbrow** [comment]
It hadn't occurred to me that the exclusions were happening on the native side because it was logging those messages and that made me think the filtering wasn't happening.  Yeah, perhaps if those messages could be suppressed from that side we wouldn't need this.  We'd have to introduce a new way to filter the logging based on some processing though since right now it just logs messages as events appear.  If you feel strongly that this is the wrong approach I can close the PR.

**Comment by bobbrow** [comment]
Discussed offline. This will be made better in the C++ part of the code.

**Pull request closed without merging**
