### PR TITLE
Use autoDetect problemMatcher.

### PR DESCRIPTION
**Pull request by sean-mcmanus**

### CODE REVIEW

**Comment by michelleangela** [comment]
Is there a work item for this or reason for using autoDetect now?

**Review by michelleangela — APPROVED** [review]

**Comment by sean-mcmanus** [comment]
> Is there a work item for this or reason for using autoDetect now?

They just added it in the most recent release of VS Code -- and the default of "relative" is bad because it fails in the default case where absolute paths are used so users have to modify the problem matcher (a user recently mentioned hitting this problem in another bug a few days ago).

**Comment by bobbrow** [comment]
mentioned in this issue: #3878

**Comment by HackerBaloo** [comment]
I still have this problem in 1.39.2 with ms-vscode.cpptools 0.26.1
I experience this problem when I compile with clang on Linux.
And I have tried to create a custom problem matcher like this:
"problemMatcher": {
        "owner": "cpp",
        "fileLocation": ["autoDetect", "${workspaceFolder}"],
        "pattern": {
          "regexp": "^(.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",
          "file": 1,
          "line": 2,
          "column": 3,
          "severity": 4,
          "message": 5
        }
      }

**Pull request merged**
