### PR TITLE
clang-format/tidy version comparisons fail for some builds

### LINKED ISSUE #12806: clang-format/tidy version comparisons fail for some builds
### Bug Summary 

When the user has installed their own version of clang-format or clang-tidy, but has not specified a specific path to the binary, we will compare one from the user's environment with the one we bundle in the extension to see which version is newer.

The logic currently expects the third token in the version query output to be the version number, but this is not always the case.  I think a more robust solution might attempt to convert each token to a semver until we find a valid one in case there are more or less tokens in the output.

RE: #12718

### PR DESCRIPTION
**Pull request by bobbrow**
Fixes: #12806

Use regular expressions to find the version number instead of token position.

### CODE REVIEW

**Review by sean-mcmanus — APPROVED** [review]
It seems theoretically possible for a custom clang build to omit a patch version, but I don't think that's normal so maybe it's okay to not support that.

**Comment by sean-mcmanus** [comment]
Is this for 1.22.8 or 1.23.0?

**Comment by bobbrow** [comment]
> It seems theoretically possible for a custom clang build to omit a patch version, but I don't think that's normal so maybe it's okay to not support that.

I suppose we can wait to see if that's a capability people ask for.

**Comment by bobbrow** [comment]
> Is this for 1.22.8 or 1.23.0?

I don't have a strong opinion. If it's not in 1.22, we may be doing a 1.23.0 pre-release shortly after.

**Comment by sean-mcmanus** [comment]
> I don't have a strong opinion. If it's not in 1.22, we may be doing a 1.23.0 pre-release shortly after.

It sounds like 1.22.8 will be a pre-release still so it seems safe enough to go into that.

**Comment by bobbrow** [comment]
ok. I'll merge this in now.

**Pull request merged**
