### PR TITLE
Added support for Toybox to remote process picker

### PR DESCRIPTION
**Pull request by michalmaka**
Hello and thanks for maintaining this repo!

I've come along a problem where my remote target needed to have different arguments for `ps` command in order to retrieve remote processes list. It was using ToyBox's `ps` and I added option for specifying custom command for getting processes list.

Current approach allows either using `ps` with different arguments or even using other command, see examples:

```
      "pipeTransport": {
        ..
        "customRemoteProcessCommand": "ps -A"
      },
```

```
      "pipeTransport": {
        ..
        "customRemoteProcessCommand": "uname && /home/root/get_pid.sh"
      },
```

One needs to have in mind that the custom command needs to return output in the same format as currently used commands do

### CODE REVIEW

**Comment by michalmaka** [comment]
microsoft-github-policy-service agree company="Software Mansion"

**Comment by michalmaka** [comment]
@microsoft-github-policy-service agree company="Software Mansion"

**Comment by WardenGnaw** [comment]
> One needs to have in mind that the custom command needs to return output in the same format as currently used commands do

This would lead to more issues for users tyring to get their command to match what `PsProcessParser` expects and make it difficult for the extension authors decide to add more columns to the process listing. If more columns were added or reorganized, this would also lead to breaking user's launch.jsons `customRemoteProcessCommand`.

We would reccomend writing a vscode input variable instead, as users can run their own vscode command and parse their own ouput to the value they want for the launch.json. 

https://code.visualstudio.com/docs/editor/variables-reference#_input-variables

E.g. launch.json
```json
{
  "configurations": [
    {
      "type": "cppdbg",
      "request": "attach",
      "name": "Run Program",
      "program": "${workspaceFolder}/a,out",
      "processId": "${input:pickProcess}"
    }
  ],
  "inputs": [
    {
      "id": "pickProcess",
      "type": "command",
      "command": "extension.my.cysto.testPicker"
    }
  ]
}
```

**Comment by michalmaka** [comment]
what about forcing such custom command to return data as CSV? Having this implemented for custom command will avoid this issue

**Comment by WardenGnaw** [comment]
> what about forcing such custom command to return data as CSV? Having this implemented for custom command will avoid this issue

That sounds good, I think there also need to be an associated field indicating the format of the output. 

E.g.
`$PID,$EXE,$CMDLINE`
and use a custom parser find those token and create the correct `Process` object.

Another question is that is there a reason why ToyBox's ps deviates from the standard usage? Is there a good way to detect that the `ps` being used is ToyBoy's version?

**Comment by michalmaka** [comment]
@WardenGnaw I've changed implementation to just support Toybox detection and proper command for getting remote process list.

For some reason Toybox's `ps` works in a bit different way.

**Review by WardenGnaw — APPROVED** [review]

**Review by sean-mcmanus — APPROVED** [review]

**Pull request merged**
