### PR TITLE
Clean up the command palette.

### PR DESCRIPTION
**Pull request by sean-mcmanus**
Address most of https://github.com/microsoft/vscode-cpptools/issues/10421 . The regex usage is based on what the TypeScript extension does (I ran across this while looking into their Extract Function support, so I decided to clean it up now).

### CODE REVIEW

**Comment by sean-mcmanus** [comment]
Do we need to file another issue to address anything else or is this good enough for now?

**Review by fearthecowboy — COMMENTED** [review]
Regexes are fun!

`/^(cuda-cpp|c|cpp)$/` might be a bit more readable but I'm not sure that it makes a differnce

**Review by fearthecowboy — DISMISSED** [review]

**Comment by sean-mcmanus** [comment]
> Regexes are fun!
> 
> `/^(cuda-cpp|c|cpp)$/` might be a bit more readable but I'm not sure that it makes a differnce

Sure, that seems better, I'll try that.

**Comment by sean-mcmanus** [comment]
I changed it to `/^(c|(cuda-)?cpp)$/` to avoid the extra -cpp.

**Review by fearthecowboy — APPROVED** [review]

**Review by michelleangela — APPROVED** [review]

**Comment by aldirenio** [comment]
ola  galera  boa  noite 
  eu  quero instalar   o  c++   e   suas  dependencias   mais  ta  osso  alquem  poria  me  ajudar

**Pull request merged**
