### PR TITLE
Fix bug: !err && stats && stats.isFile will always return true. Fix typos

### PR DESCRIPTION
**Pull request by inlann**
Hello:

I found the `if(!err && stats && stats.isFile)` in the `src/Debugger/configurationProvider`  will always return true. It should be `if(!err && stats && stats.isFile())`.

Also found some typos and fixed them 😄

### CODE REVIEW

**Comment by inlann** [comment]
Hello:

Do I need to review it myself or wait for someone?

**Comment by bobbrow** [comment]
We will review and commit it.  Monday was a holiday for MSFT so no one had a chance to look yet.

**Review by bobbrow — APPROVED** [review]

**Review by sean-mcmanus — APPROVED** [review]

**Comment by inlann** [comment]
Thanks 😄 

BTW: I cloned the source code of cpptools and debugged it in VSCode via F5. But I got the binary missing error:

`Unable to start the C/C++ language server. IntelliSense features will be disabled. Error: Missing binary at /Users/mac/Work/vscode-cpptools-inlann/Extension/bin/cpptools`

image

I checked the cpptools vsix package downloaded from [ms market](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools) and there are two executable files `cpptools` and `cpptools-srv` in the `bin` folder. How can I generate them if I modify the source code of the extension?

**Comment by sean-mcmanus** [comment]
> Thanks 😄
> 
> BTW: I cloned the source code of cpptools and debugged it in VSCode via F5. But I got the binary missing error:
> 
> `Unable to start the C/C++ language server. IntelliSense features will be disabled. Error: Missing binary at /Users/mac/Work/vscode-cpptools-inlann/Extension/bin/cpptools`
> 
> image
> 
> I checked the cpptools vsix package downloaded from [ms market](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools) and there are two executable files `cpptools` and `cpptools-srv` in the `bin` folder. How can I generate them if I modify the source code of the extension?

See https://github.com/microsoft/vscode-cpptools/blob/main/Documentation/Building%20the%20Extension.md

**Comment by inlann** [comment]
> See https://github.com/microsoft/vscode-cpptools/blob/main/Documentation/Building%20the%20Extension.md

Thank you for your response!

The [document](https://github.com/microsoft/vscode-cpptools/blob/main/Documentation/Building%20the%20Extension.md) says I need to download the cpptools extension from the Visual Studio Marketplace and copy its binaries `cpptools` and `cpptools-srv` into my `bin` folder. Does this mean that I do not need to generate the `cpptools` and `cpptools-srv` binaries myself even if I modify the typescript source code in `src` directory?

**Comment by sean-mcmanus** [comment]
@inlann Yes, you can't generate the cpptools and cpptools-srv binaries -- changing the TypeScript doesn't affect the binaries.

**Comment by inlann** [comment]
@sean-mcmanus Thanks so much 😄  That's really helpful

**Pull request merged**
