### PR TITLE
reports the correct __cplusplus macro for MSVC IntelliSense Mode

### PR DESCRIPTION
**Pull request by elahehrashedi**
feature-request: https://github.com/microsoft/vscode-cpptools/issues/2595
the language-server side is also altered to accommodate this feature. 
The reason I am adding a default value for _Cplusplus is that if the IntelliSense mode is MSVC and the std version is c++17, the default value for _cplusplus is  201703L.

### CODE REVIEW

**Comment by sean-mcmanus** [comment]
How does this work? I wouldn't think "/Zc" would be a valid define. It would think it would have be passed as a compilerArg, although then cpptools would have to be updated to process that.

**Comment by bobbrow** [comment]
~~Does cl.exe set this by default in newer versions?~~  You have to opt in.  I didn't expect to see any change to the TypeScript for this issue.

EDIT: From: https://devblogs.microsoft.com/cppblog/msvc-now-correctly-reports-__cplusplus/
You need to compile with the `/Zc:__cplusplus` switch to see the updated value of the `__cplusplus` macro. We tried updating the macro by default and discovered that a lot of code doesn’t compile correctly when we change the value of `__cplusplus`. **We’ll continue to require use of the `/Zc:__cplusplus` switch for all minor versions of MSVC in the 19.xx family.**

**Comment by sean-mcmanus** [comment]
> ~Does cl.exe set this by default in newer versions?~ You have to opt in. I didn't expect to see any change to the TypeScript for this issue.
> 
> EDIT: From: https://devblogs.microsoft.com/cppblog/msvc-now-correctly-reports-__cplusplus/
> You need to compile with the `/Zc:__cplusplus` switch to see the updated value of the `__cplusplus` macro. We tried updating the macro by default and discovered that a lot of code doesn’t compile correctly when we change the value of `__cplusplus`. **We’ll continue to require use of the `/Zc:__cplusplus` switch for all minor versions of MSVC in the 19.xx family.**

That seems to imply we shouldn't change the defaults?

**Comment by bobbrow** [comment]
We shouldn't change the defaults for now.  When the compiler updates the version to 20.xx we may have to make some changes, but we're still on 19.xx now.

**Pull request closed without merging**
