### PR TITLE
Fix bug introduced by #11175

### LINKED ISSUE #11328: The Remote attach to process command has been reversed between Linux and Darwin
### Environment

- OS and version:
- VS Code:
- C/C++ extension:
- OS and version of remote machine (if applicable):
- GDB / LLDB version:

### Bug Summary and Steps to Reproduce

Bug Summary:

Run a Linux container ( any Centos/RHEL/) and then run a program there from a Mac. When the debugger tries to attach, it will fail to attach because the attach commands have been switched. in the commit a7870fc

So the Darwin command is now getting run on Linux and that is causing the debugger to not attach

See attachtoprocess.ts

        return `${outerQuote}${shPrefix}sh -c ${innerQuote}uname && if [ ${parameterBegin}uname -o${parameterEnd} = ${escapedQuote}Toybox${escapedQuote} ] ; ` +
            `then ${PsProcessParser.psToyboxCommand} ; elif [ ${parameterBegin}uname${parameterEnd} = ${escapedQuote}Darwin${escapedQuote} ] ; ` +
            `then ${PsProcessParser.psLinuxCommand} ; elif [ ${parameterBegin}uname${parameterEnd} = ${escapedQuote}Linux${escapedQuote} ] ; ` +
            `then ${PsProcessParser.psDarwinCommand}; fi${innerQuote}${outerQuote}`;
    }

This was the PR that made this issue
a7870fc1b26f783ef0c7570ad2a7c84abe21bdb1

### Debugger Configurations

```shell
"configurations": [
        {
            "name": "(lldb) modlog-Attach",
            "type": "cppdbg",
            "request": "attach",
            "program": "/Users/parag.paul/snc/modlog_reader/build/modlog_reader",
            "processId": "${command:pickRemoteProcess}",
            "MIMode": "gdb",
            "pipeTransport": {
                "pipeCwd": "${workspaceRoot}",
                "pipeProgram": "/Users/parag.paul/tembo/tembo/tools/docker_exec_last_container.sh",
                "pipeArgs": [
                    "sh", 
                    "-c"
                ],
                "debuggerPath": "/usr/bin/gdb"
            }
        },
```

### Debugger Logs

```shell
No need for logs.
```

### Other Extensions

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by bobbrow**
Fixes https://github.com/microsoft/vscode-cpptools/issues/11328, a bug introduced by PR #11175

### CODE REVIEW

**Review by rahiakil — APPROVED** [review]

**Comment by rahiakil** [comment]
How does one build the extension on Mac(M1) . I am on a Mac M1 and need this extension urgently. How quickly can you push and publish this extension

**Comment by sean-mcmanus** [comment]
> How does one build the extension on Mac(M1) . I am on a Mac M1 and need this extension urgently. How quickly can you push and publish this extension

You could downgrade to 1.16.3?

**Comment by sean-mcmanus** [comment]
@bobbrow How did you find this bug?

**Review by sean-mcmanus — APPROVED** [review]

**Comment by sean-mcmanus** [comment]
> @bobbrow How did you find this bug? i.e. was it reported by a user?

Oh, I see now, @rahiakil reported it in the PR.

**Comment by rahiakil** [comment]
> @bobbrow How did you find this bug? i.e. was it reported by a user?

hi Bob/Sean, Ex SQL Server engineer here. Love the work you are doing. I am no longer with Microsoft. But I debugged this today when after upgrading the extension I saw that I cannot connect ( of course due to the ps -c switch between Darwin and Linux).  Happy to contribute across company boundaries

**Comment by rahiakil** [comment]
> > How does one build the extension on Mac(M1) . I am on a Mac M1 and need this extension urgently. How quickly can you push and publish this extension
> 
> You could downgrade to 1.16.3?

yes, I did that.

**Review by Colengms — APPROVED** [review]

**Review by michelleangela — APPROVED** [review]

**Comment by bobbrow** [comment]
> How does one build the extension on Mac(M1) . I am on a Mac M1 and need this extension urgently. How quickly can you push and publish this extension

You can edit the `.js` on your machine directly while you wait for us to publish this.  It should be in `~/.vscode/extensions/ms-vscode.cpptools-1.17.2-darwin-arm64/dist/main.js`.  Search for the strings in the PR and swap the order.

**Pull request merged**
